import Head from 'next/head'
import Image from 'next/image'
import {
  Container,
  Box,
  Link,
  Stack,
  Heading,
  Flex,
  useColorModeValue
} from '@chakra-ui/react'
import styles from '../styles/Home.module.css'
import styled from '@emotion/styled'


export default function Home() {

  const HuluImg = `/images/hulu.svg`
  const NetflixImg = `/images/netflix.svg`

  const HeroSection = styled.span`
  font-weight: bold;
  font-size: 36px;
  align-items: center;
  height: 40px;
  line-height: 30px;
  padding: 20px;
  img {
    transition: 200ms ease;
  }
  &:hover img {
    transform: rotate(10deg);
  }
`


  return (
    <div className={styles.container}>
      <Head>
        <title>StreamEZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroSection>
        <h1>Can't find <strong><em>where</em></strong> to watch?</h1>
        <div>
            <Image src={NetflixImg} width={200} height={100} alt="netflix" />
            <Image src={HuluImg} width={200} height={100} alt="hulu" />
          </div>
        </HeroSection>
        <br/>     
        <br/>     
        <br/>     
        <br/>     
        <br/>     

        <div className={styles.grid}>
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
